### PR TITLE
Style improvements

### LINKED ISSUE #48: The all Ouija block is selected after hitting submit button
Gifs speaks the truth.

See what i mean?

I need to focus elsewhere which closes Ouija or focus in the textarea to unselect.

### PR DESCRIPTION
**Pull request by ntassone**
Fixes #48 
- Removes the `user-select` rule on the comment drawer. The `visibility: hidden` and `visible` rules take care of making the text un-selectable when hidden.
- Author link to twitter now opens in a new window
- Firefox was showing a dotted line on focus of the ouija controls, that is now hidden

### CODE REVIEW

**Comment by halfdan** [comment]
I think this one can be rebased now - will need conversion from jsx syntax though.

**Comment by colinmacdonald** [comment]
Added the `target=_blank` to your branch @ntassone

**Comment by colinmacdonald** [comment]
rebased this one.

**Comment by halfdan** [comment]
:+1: LGTM

**Pull request merged**
