### PR TITLE
Colophon

### LINKED ISSUE #47: Add colophon
Show a "Powered by [Ouija](http://ouija.io)" message at the bottom of the Ouija drawer.

### PR DESCRIPTION
**Pull request by ntassone**
Fixes #47, adds a "Powered by Ouija" footer to the comment threads:

### CODE REVIEW

**Comment by halfdan** [comment]
Can this be merged/rebased after my PR is in? Would make a complete mess otherwise :)

**Comment by ntassone** [comment]
@halfdan sure thing :ok_hand:

**Comment by colinmacdonald** [comment]
LGTM

**Comment by halfdan** [comment]
@ntassone Just as a tip: `git rebase master` is a bit better than merging. It replays your changes onto the current stuff from master, keeping the commit history intact.

**Pull request merged**
